import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { HeroSection } from "../components/HeroSection";
import { CustomersLogoSection } from "../components/CustomersLogoSection";
import { PlatformSection } from "../components/PlatformSection";
import { DataSection } from "../components/DataSection";
import { FeatureWithPictureSection } from "../components/FeatureWithPictureSection";
import { CardSection } from "../components/CardSection";
import { ReviewSection } from "../components/ReviewSection";
import { CtaSection } from "../components/CtaSection";
import { Footer } from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className="overflow-x-hidden lg:bg-[url('/graphics/illustrations.svg')] lg:bg-[right_-46.5625rem_top_-50.625rem] lg:bg-no-repeat 2xl:bg-[right_-39.0625rem_top_-50.625rem]">
      <Head>
        <title>SaaS Platform Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mx-auto max-w-[90rem]">
        <Header />
      </header>
      <main className="mx-auto flex max-w-[90rem] flex-col items-center justify-center">
        <HeroSection />
        <CustomersLogoSection />
        <PlatformSection />
        <DataSection />
        <FeatureWithPictureSection />
        <CardSection />
        <ReviewSection />
        <CtaSection />
      </main>
      <footer className="mt-[9.375rem] px-4 sm:px-[6.25rem]">
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
